<a href="https://colab.research.google.com/github/i-nitishh/Deep-Learning/blob/Customer_Churn_Modelling(ANN)/Customer_Churn_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/krishnaik06/Complete-Deep-Learning/master/ANN/Churn_Modelling.csv')

In [ ]:
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [ ]:
import tensorflow.keras as keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

In [ ]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [ ]:
x = df[df.columns[3:-2]]
x

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  
0             1               1  
1             0               1  
2             1               0  
3             0               0  
4             1               1  
...         ...             ...  
9995          1               0  
9996          1               1  
9997          0               1  
9998          1               0  
9999          1               0  

[10000 rows x 9 columns]

In [ ]:
y = df[df.columns[-1]]
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [ ]:
df2 =pd.get_dummies(x['Geography'])

In [ ]:
x = pd.concat([x,df2],axis=1)
x = x.drop(['Geography'],axis =1)

In [ ]:
x.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619  Female   42       2       0.00              1          1   
1          608  Female   41       1   83807.86              1          0   
2          502  Female   42       8  159660.80              3          1   
3          699  Female   39       1       0.00              2          0   
4          850  Female   43       2  125510.82              1          1   

   IsActiveMember  France  Germany  Spain  
0               1       1        0      0  
1               1       0        0      1  
2               0       1        0      0  
3               0       1        0      0  
4               1       0        0      1

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()
x['Gender'] = le.fit_transform(x[['Gender']])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
x

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619       0   42       2       0.00              1          1   
1             608       0   41       1   83807.86              1          0   
2             502       0   42       8  159660.80              3          1   
3             699       0   39       1       0.00              2          0   
4             850       0   43       2  125510.82              1          1   
...           ...     ...  ...     ...        ...            ...        ...   
9995          771       1   39       5       0.00              2          1   
9996          516       1   35      10   57369.61              1          1   
9997          709       0   36       7       0.00              1          0   
9998          772       1   42       3   75075.31              2          1   
9999          792       0   28       4  130142.79              1          1   

      IsActiveMember  France  Germany  Spain  
0                  1       1        0      0  
1                  1       0        0      1  
2                  0       1        0      0  
3                  0       1        0      0  
4                  1       0        0      1  
...              ...     ...      ...    ...  
9995               0       1        0      0  
9996               1       1        0      0  
9997               1       1        0      0  
9998               0       0        1      0  
9999               0       1        0      0  

[10000 rows x 11 columns]

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
se = StandardScaler()
x = se.fit_transform(x)

In [ ]:
x = pd.DataFrame(x)

In [ ]:
x

0         1         2         3         4         5         6   \
0    -0.326221 -1.095988  0.293517 -1.041760 -1.225848 -0.911583  0.646092   
1    -0.440036 -1.095988  0.198164 -1.387538  0.117350 -0.911583 -1.547768   
2    -1.536794 -1.095988  0.293517  1.032908  1.333053  2.527057  0.646092   
3     0.501521 -1.095988  0.007457 -1.387538 -1.225848  0.807737 -1.547768   
4     2.063884 -1.095988  0.388871 -1.041760  0.785728 -0.911583  0.646092   
...        ...       ...       ...       ...       ...       ...       ...   
9995  1.246488  0.912419  0.007457 -0.004426 -1.225848  0.807737  0.646092   
9996 -1.391939  0.912419 -0.373958  1.724464 -0.306379 -0.911583  0.646092   
9997  0.604988 -1.095988 -0.278604  0.687130 -1.225848 -0.911583 -1.547768   
9998  1.256835  0.912419  0.293517 -0.695982 -0.022608  0.807737  0.646092   
9999  1.463771 -1.095988 -1.041433 -0.350204  0.859965 -0.911583  0.646092   

            7         8         9         10  
0     0.970243  0.997204 -0.578736 -0.573809  
1     0.970243 -1.002804 -0.578736  1.742740  
2    -1.030670  0.997204 -0.578736 -0.573809  
3    -1.030670  0.997204 -0.578736 -0.573809  
4     0.970243 -1.002804 -0.578736  1.742740  
...        ...       ...       ...       ...  
9995 -1.030670  0.997204 -0.578736 -0.573809  
9996  0.970243  0.997204 -0.578736 -0.573809  
9997  0.970243  0.997204 -0.578736 -0.573809  
9998 -1.030670 -1.002804  1.727904 -0.573809  
9999 -1.030670  0.997204 -0.578736 -0.573809  

[10000 rows x 11 columns]

In [ ]:
x

0         1         2         3         4         5         6   \
0    -0.326221 -1.095988  0.293517 -1.041760 -1.225848 -0.911583  0.646092   
1    -0.440036 -1.095988  0.198164 -1.387538  0.117350 -0.911583 -1.547768   
2    -1.536794 -1.095988  0.293517  1.032908  1.333053  2.527057  0.646092   
3     0.501521 -1.095988  0.007457 -1.387538 -1.225848  0.807737 -1.547768   
4     2.063884 -1.095988  0.388871 -1.041760  0.785728 -0.911583  0.646092   
...        ...       ...       ...       ...       ...       ...       ...   
9995  1.246488  0.912419  0.007457 -0.004426 -1.225848  0.807737  0.646092   
9996 -1.391939  0.912419 -0.373958  1.724464 -0.306379 -0.911583  0.646092   
9997  0.604988 -1.095988 -0.278604  0.687130 -1.225848 -0.911583 -1.547768   
9998  1.256835  0.912419  0.293517 -0.695982 -0.022608  0.807737  0.646092   
9999  1.463771 -1.095988 -1.041433 -0.350204  0.859965 -0.911583  0.646092   

            7         8         9         10  
0     0.970243  0.997204 -0.578736 -0.573809  
1     0.970243 -1.002804 -0.578736  1.742740  
2    -1.030670  0.997204 -0.578736 -0.573809  
3    -1.030670  0.997204 -0.578736 -0.573809  
4     0.970243 -1.002804 -0.578736  1.742740  
...        ...       ...       ...       ...  
9995 -1.030670  0.997204 -0.578736 -0.573809  
9996  0.970243  0.997204 -0.578736 -0.573809  
9997  0.970243  0.997204 -0.578736 -0.573809  
9998 -1.030670 -1.002804  1.727904 -0.573809  
9999 -1.030670  0.997204 -0.578736 -0.573809  

[10000 rows x 11 columns]

In [ ]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size = 0.2 , random_state =0)

In [ ]:
model = Sequential()

In [ ]:
model.add(Dense(units = 10 ,activation = 'relu' , input_shape = (11,) ,kernel_initializer = 'he_uniform'))
model.add(Dropout(0.2))
model.add(Dense(units = 16 ,activation = 'relu' ,kernel_initializer = 'he_uniform'))
model.add(Dropout(0.1))
model.add(Dense(units = 1 ,activation = 'sigmoid' ,kernel_initializer = 'glorot_uniform'))

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_8 (Dense)             (None, 10)                120       
                                                                 
 dropout_7 (Dropout)         (None, 10)                0         
                                                                 
 dense_9 (Dense)             (None, 16)                176       
                                                                 
 dropout_8 (Dropout)         (None, 16)                0         
                                                                 
 dense_10 (Dense)            (None, 1)                 17        
                                                                 
Total params: 313
Trainable params: 313
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(optimizer = 'adam' , loss = 'binary_crossentropy', metrics =['accuracy'])

In [ ]:
model.fit(x_train,y_train , validation_split =0.3 ,batch_size =10 ,epochs = 100)

Epoch 1/100
560/560 [==============================] - 2s 4ms/step - loss: 0.4181 - accuracy: 0.8170 - val_loss: 0.4175 - val_accuracy: 0.8200
Epoch 2/100
560/560 [==============================] - 3s 5ms/step - loss: 0.4178 - accuracy: 0.8216 - val_loss: 0.4174 - val_accuracy: 0.8221
Epoch 3/100
560/560 [==============================] - 2s 4ms/step - loss: 0.4165 - accuracy: 0.8157 - val_loss: 0.4162 - val_accuracy: 0.8221
Epoch 4/100
560/560 [==============================] - 3s 5ms/step - loss: 0.4163 - accuracy: 0.8180 - val_loss: 0.4159 - val_accuracy: 0.8200
Epoch 5/100
560/560 [==============================] - 2s 4ms/step - loss: 0.4164 - accuracy: 0.8204 - val_loss: 0.4184 - val_accuracy: 0.8192
Epoch 6/100
560/560 [==============================] - 2s 4ms/step - loss: 0.4133 - accuracy: 0.8175 - val_loss: 0.4157 - val_accuracy: 0.8200
Epoch 7/100
560/560 [==============================] - 2s 4ms/step - loss: 0.4105 - accuracy: 0.8221 - val_loss: 0.4145 - val_accuracy: 0.8213

In [ ]:
y_pred = model.predict(x_test)
y_pred = (y_pred>0.5)

63/63 [==============================] - 0s 1ms/step


In [ ]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_pred , y_test)
cm

array([[1526,  206],
       [  69,  199]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred , y_test)

0.8625

In [ ]:
## HyperParameter Tunning

In [ ]:
def build_up(hp):
  counter = 0
  model = Sequential()
  for i in range(hp.Int('layer_no' , min_value = 1 ,max_value = 10)):
    if counter ==0:
      model.add(Dense(hp.Int('units' + str(i), min_value = 8 , max_value = 128 , step =16),
                      activation = hp.Choice('activation'+str(i), values = ['relu','tanh','sigmoid','elu','LeakyReLU']),
                      kernel_initializer=hp.Choice('ki'+str(i),values = ['glorot_normal','glorot_uniform','he_uniform','he_normal']),
                      input_dim =11))
      model.add(Dropout(hp.Choice('dropout'+str(i) , values = [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9])))
    else:
         model.add(Dense(hp.Int('units' + str(i), min_value = 8 , max_value = 128 , step =1),
                      activation = hp.Choice('activation'+str(i), values = ['relu','tanh','sigmoid','elu','LeakyReLU']),
                      kernel_initializer=hp.Choice('ki'+str(i),values = ['glorot_normal','glorot_uniform','he_uniform','he_normal'])))
         model.add(Dropout(hp.Choice('dropout'+str(i) , values = [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9])))
  model.add(Dense(1,activation = 'sigmoid'))
  model.compile(optimizer=hp.Choice('optimizer',values = ['adam','rmsprop','adadelta']),loss = 'binary_crossentropy',metrics = ['accuracy'])
  return model

In [ ]:
pip install keras_tuner

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import keras_tuner as kt

In [ ]:
tuner = kt.RandomSearch(build_up , objective ='val_accuracy',max_trials = 5 , directory = 'mydir',project_name ='customer_churn')

In [ ]:
tuner.search(x_train,y_train , epochs =5 , validation_split =0.3)

In [ ]:
tuner.get_best_hyperparameters()[0].values

{'layer_no': 7,
 'units0': 114,
 'activation0': 'LeakyReLU',
 'ki0': 'glorot_normal',
 'optimizer': 'adam',
 'units1': 83,
 'activation1': 'elu',
 'ki1': 'glorot_uniform',
 'units2': 16,
 'activation2': 'relu',
 'ki2': 'glorot_normal',
 'units3': 67,
 'activation3': 'sigmoid',
 'ki3': 'glorot_uniform',
 'units4': 124,
 'activation4': 'elu',
 'ki4': 'glorot_normal',
 'units5': 80,
 'activation5': 'relu',
 'ki5': 'glorot_normal',
 'units6': 96,
 'activation6': 'sigmoid',
 'ki6': 'he_normal',
 'units7': 38,
 'activation7': 'elu',
 'ki7': 'he_normal'}

In [ ]:
models = tuner.get_best_models(num_models=1)[0]

In [ ]:
models.fit(x_train,y_train , validation_split =0.3 , batch_size =30 , epochs =100 )

Epoch 1/100
187/187 [==============================] - 6s 7ms/step - loss: 0.3675 - accuracy: 0.8452 - val_loss: 0.3526 - val_accuracy: 0.8546
Epoch 2/100
187/187 [==============================] - 1s 6ms/step - loss: 0.3569 - accuracy: 0.8495 - val_loss: 0.3566 - val_accuracy: 0.8587
Epoch 3/100
187/187 [==============================] - 1s 6ms/step - loss: 0.3529 - accuracy: 0.8546 - val_loss: 0.3561 - val_accuracy: 0.8575
Epoch 4/100
187/187 [==============================] - 1s 7ms/step - loss: 0.3455 - accuracy: 0.8600 - val_loss: 0.3677 - val_accuracy: 0.8483
Epoch 5/100
187/187 [==============================] - 1s 8ms/step - loss: 0.3508 - accuracy: 0.8568 - val_loss: 0.3638 - val_accuracy: 0.8587
Epoch 6/100
187/187 [==============================] - 1s 6ms/step - loss: 0.3521 - accuracy: 0.8545 - val_loss: 0.3549 - val_accuracy: 0.8529
Epoch 7/100
187/187 [==============================] - 1s 6ms/step - loss: 0.3464 - accuracy: 0.8550 - val_loss: 0.3546 - val_accuracy: 0.8592

In [ ]:
y_fpred = models.predict(x_test)

63/63 [==============================] - 0s 2ms/step


In [ ]:
y_fpred = (y_pred>0.5)

In [ ]:
y_fpred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [ ]:
cm1 = confusion_matrix(y_fpred , y_test)

In [ ]:
cm1

array([[1526,  206],
       [  69,  199]])

In [ ]:
accuracy_score(y_fpred , y_test)

0.8625